/* eslint-disable */
// Config declarativa de los 7 formatos de pre-comisionamiento de equipos.
// El texto de los ítems se lee VERBATIM del .xls; aquí solo se declaran
// identidad, opciones de resultado y los TÍTULOS DE SECCIÓN (para separar
// secciones de ítems, ya que el .xls no tiene señal estructural fiable).
//
// resultOptions: opciones del checkbox por ítem (tal cual el formato).
// sectionTitles: textos (normalizados por comparación laxa) que inician sección.
// resultado: si existe fila RESULTADO/APROBADO al pie → select con esas opciones.

module.exports = [
  {
    file: "B1 a B10 FormatoPre-ComisionaBombaRECIRCULACION.xls",
    sheet: "PBombaRecirLodo",
    key: "P_EFL-019",
    name: "Bomba de Recirculación de Lodos",
    equipmentType: "BOMBA_CENTRIFUGA",
    alcance: null,
    revision: "Jun-09 (versión cero)",
    resultOptions: ["Cumple", "No cumple", "N/A"],
    defaultSection: "Datos de Placa",
    sectionTitles: [
      "Instalaciones y estructuras para la bomba",
      "Bomba",
      "Insntrumentos e Instrumentacion Bomba",
      "Motor de Bomba (completar con formato inspeccion motor, parte electrica)",
      "Documentacion",
    ],
    resultado: null,
  },
  {
    file: "SC1 y SC2 parte 2 FormatoPre-ComisionaBombaCHILLER.xls",
    sheet: "PBombaChiller",
    key: "P_BIO-006",
    name: "Chiller — Bomba e Instrumentación (con instrumentos)",
    equipmentType: "CHILLER",
    alcance: "con_instrumentos",
    revision: "Jun-09 (versión cero)",
    resultOptions: ["Cumple", "No cumple", "N/A"],
    defaultSection: "Datos de Placa",
    sectionTitles: [
      "Instalaciones y estructuras para la bomba",
      "Bomba",
      "Instrumentacion Bomba",
      "Motor de Bomba",
      "Documentacion",
    ],
    resultado: null,
  },
  {
    file: "SC1 y SC2 parte 1 FormatoPre-Comisionamiento Chiller.xls",
    sheet: "PCHILLER",
    key: "P_BIO-005",
    name: "Chiller — Montaje Mecánico (sin instrumentos)",
    equipmentType: "CHILLER",
    alcance: "sin_instrumentos",
    revision: "Jun-09 (Ver. 0)",
    resultOptions: ["Conforme", "No conforme", "N/A"],
    defaultSection: "Instalación del Chiller",
    sectionTitles: [],
    resultado: null,
  },
  {
    file: "GE-01 Formato Pre-ComisionaGeneradorEmergencia.xls",
    sheet: "PGenerador",
    key: "P_ELE-025",
    name: "Generador de Emergencia",
    equipmentType: "GENERADOR_EMERGENCIA",
    alcance: null,
    revision: "Jun-09 (versión cero)",
    resultOptions: ["Cumple", "No cumple", "N/A"],
    defaultSection: "Datos de Placa",
    sectionTitles: [
      "Instalaciones y estructuras",
      "Motor del Grupo",
      "Sistema de alimentacion de Combustible",
      "Exhosto",
      "Generador",
      "Instrumentacion",
      "Documentacion",
    ],
    resultado: { label: "Resultado", options: ["APROBADO", "RECHAZADO"] },
  },
  {
    file: "TC-01 FormatoPre y Comisionamiento-TEA.xls",
    sheet: "PTea",
    key: "P_BIO-020",
    name: "Tea — Aprovechamiento de Biogás",
    equipmentType: "TEA",
    alcance: null,
    revision: "Jun-09 (versión cero)",
    resultOptions: ["Conforme", "No conforme", "N/A"],
    defaultSection: "Datos de Placa",
    sectionTitles: [
      "Instalaciones y estructuras soporte",
      "Cuerpoy estructura TEA",
      "Instrumentacion",
      "Documentacion",
    ],
    resultado: { label: "Resultado", options: ["APROBADO", "RECHAZADO"] },
  },
  {
    file: "S1 a S4 FormPre-ComisionSoplador.xls",
    sheet: "Chequeo",
    key: "P_BIO-010",
    name: "Soplador de Biogás",
    equipmentType: "SOPLADOR",
    alcance: null,
    revision: "Jun-09 (Ver. 0)",
    resultOptions: ["Conforme", "No conforme", "N/A"],
    defaultSection: "Verificación del Soplador",
    sectionTitles: [],
    resultado: { label: "Resultado", options: ["APROBADO", "RECHAZADO"] },
  },
  {
    file: "SA1 a SA3 FormatoPre-Comisionamiento Solpadores de aire.xls",
    sheet: "PCompresor",
    key: "P_BIO-002",
    name: "Sopladores de Aire",
    equipmentType: "SOPLADOR",
    alcance: null,
    revision: "Jun-09 (versión cero)",
    resultOptions: ["Conforme", "No conforme", "N.A."],
    defaultSection: "Lista de Chequeo",
    sectionTitles: [
      "ESPECIFICACIONES TECNICAS",
      "ESPECIFICACIONES TECNICAS INDICADOR DE PRESION",
      "Documentacion",
    ],
    resultado: { label: "Resultado", options: ["SÍ", "NO", "CON RESTRICCIÓN"] },
  },
];
